# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QHBoxLayout,
    QLabel, QMainWindow, QPushButton, QScrollArea,
    QSizePolicy, QVBoxLayout, QWidget)
import rc_resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1200, 600)
        MainWindow.setMaximumSize(QSize(16777215, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(18, 18, 18, 200))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setWindowOpacity(0.950000000000000)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(25, 25))
        self.centralwidget.setBaseSize(QSize(0, 0))
        self.horizontalLayout_5 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, -102, 1184, 750))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        palette1 = QPalette()
        brush1 = QBrush(QColor(4, 12, 6, 200))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.scrollAreaWidgetContents.setPalette(palette1)
        self.verticalLayout = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 25, 0, 0)
        self.widget = QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName(u"widget")
        self.widget.setMinimumSize(QSize(0, 375))
        self.widget.setMaximumSize(QSize(16777215, 375))
        self.widget.setBaseSize(QSize(0, 375))
        self.verticalLayout_2 = QVBoxLayout(self.widget)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.widget_2 = QWidget(self.widget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setMaximumSize(QSize(500, 50))
        self.horizontalLayout_2 = QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.widget_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy1)
        self.label_2.setMinimumSize(QSize(25, 25))
        self.label_2.setMaximumSize(QSize(50, 50))
        self.label_2.setSizeIncrement(QSize(0, 0))
        self.label_2.setBaseSize(QSize(25, 25))
        self.label_2.setStyleSheet(u"image: url(:/icons/resources/icons/steam-icon.png);")
        self.label_2.setPixmap(QPixmap(u":/icons/resources/icons/steam-icon.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setMargin(0)

        self.horizontalLayout_2.addWidget(self.label_2)

        self.label = QLabel(self.widget_2)
        self.label.setObjectName(u"label")
        self.label.setEnabled(False)
        self.label.setMinimumSize(QSize(25, 25))
        self.label.setMaximumSize(QSize(100, 50))
        self.label.setBaseSize(QSize(25, 25))
        font = QFont()
        font.setPointSize(24)
        font.setStyleStrategy(QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.horizontalLayout_2.addWidget(self.label)

        self.connect_steam = QPushButton(self.widget_2)
        self.connect_steam.setObjectName(u"connect_steam")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.connect_steam.sizePolicy().hasHeightForWidth())
        self.connect_steam.setSizePolicy(sizePolicy2)
        self.connect_steam.setMaximumSize(QSize(100, 50))
        palette2 = QPalette()
        brush2 = QBrush(QColor(66, 66, 66, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        self.connect_steam.setPalette(palette2)
        font1 = QFont()
        font1.setFamilies([u"Inter"])
        font1.setPointSize(12)
        self.connect_steam.setFont(font1)
        self.connect_steam.setCursor(QCursor(Qt.PointingHandCursor))
        self.connect_steam.setFlat(False)

        self.horizontalLayout_2.addWidget(self.connect_steam)

        self.change_steam_directory = QPushButton(self.widget_2)
        self.change_steam_directory.setObjectName(u"change_steam_directory")
        sizePolicy2.setHeightForWidth(self.change_steam_directory.sizePolicy().hasHeightForWidth())
        self.change_steam_directory.setSizePolicy(sizePolicy2)
        self.change_steam_directory.setMaximumSize(QSize(175, 50))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        self.change_steam_directory.setPalette(palette3)
        self.change_steam_directory.setFont(font1)
        self.change_steam_directory.setCursor(QCursor(Qt.PointingHandCursor))
        self.change_steam_directory.setText(u"\ud83d\udcc1 Change directory")
        self.change_steam_directory.setFlat(False)

        self.horizontalLayout_2.addWidget(self.change_steam_directory)


        self.verticalLayout_2.addWidget(self.widget_2)

        self.widget_3 = QWidget(self.widget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setMaximumSize(QSize(16777215, 50))
        self.horizontalLayout = QHBoxLayout(self.widget_3)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_6 = QLabel(self.widget_3)
        self.label_6.setObjectName(u"label_6")
        font2 = QFont()
        font2.setPointSize(18)
        self.label_6.setFont(font2)
        self.label_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.label_6)


        self.verticalLayout_2.addWidget(self.widget_3)

        self.widget_5 = QWidget(self.widget)
        self.widget_5.setObjectName(u"widget_5")
        self.verticalLayout_4 = QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(75, 0, 75, 0)
        self.Steam_recent_games_2 = QScrollArea(self.widget_5)
        self.Steam_recent_games_2.setObjectName(u"Steam_recent_games_2")
        self.Steam_recent_games_2.setEnabled(True)
        self.Steam_recent_games_2.setMinimumSize(QSize(0, 0))
        self.Steam_recent_games_2.setMaximumSize(QSize(16777215, 242))
        self.Steam_recent_games_2.setStyleSheet(u"")
        self.Steam_recent_games_2.setFrameShape(QFrame.NoFrame)
        self.Steam_recent_games_2.setFrameShadow(QFrame.Sunken)
        self.Steam_recent_games_2.setLineWidth(2)
        self.Steam_recent_games_2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.Steam_recent_games_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Steam_recent_games_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.Steam_recent_games_2.setWidgetResizable(True)
        self.Steam_recent_games = QWidget()
        self.Steam_recent_games.setObjectName(u"Steam_recent_games")
        self.Steam_recent_games.setEnabled(True)
        self.Steam_recent_games.setGeometry(QRect(0, 0, 1014, 238))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.Steam_recent_games.sizePolicy().hasHeightForWidth())
        self.Steam_recent_games.setSizePolicy(sizePolicy3)
        self.Steam_recent_games.setMinimumSize(QSize(0, 0))
        self.Steam_recent_games.setMaximumSize(QSize(16777215, 238))
        palette4 = QPalette()
        brush3 = QBrush(QColor(4, 12, 6, 100))
        brush3.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(4, 12, 6, 225))
        brush4.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush4)
        brush5 = QBrush(QColor(105, 105, 105, 200))
        brush5.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        brush6 = QBrush(QColor(74, 84, 89, 225))
        brush6.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Shadow, brush5)
        palette4.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Accent, brush6)
        self.Steam_recent_games.setPalette(palette4)
        self.Steam_recent_games.setStyleSheet(u"")
        self.horizontalLayout_3 = QHBoxLayout(self.Steam_recent_games)
        self.horizontalLayout_3.setSpacing(8)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.Steam_recent_games_2.setWidget(self.Steam_recent_games)

        self.verticalLayout_4.addWidget(self.Steam_recent_games_2)


        self.verticalLayout_2.addWidget(self.widget_5)


        self.verticalLayout.addWidget(self.widget)

        self.widget_4 = QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setMinimumSize(QSize(0, 350))
        self.widget_4.setMaximumSize(QSize(16777215, 374))
        self.widget_4.setBaseSize(QSize(0, 375))
        self.verticalLayout_3 = QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.widget_6 = QWidget(self.widget_4)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setMaximumSize(QSize(16777215, 50))
        self.horizontalLayout_9 = QHBoxLayout(self.widget_6)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.label_37 = QLabel(self.widget_6)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setFont(font2)
        self.label_37.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_37.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_9.addWidget(self.label_37)


        self.verticalLayout_3.addWidget(self.widget_6)

        self.Steam_recent_games_3 = QScrollArea(self.widget_4)
        self.Steam_recent_games_3.setObjectName(u"Steam_recent_games_3")
        self.Steam_recent_games_3.setEnabled(True)
        self.Steam_recent_games_3.setMinimumSize(QSize(0, 0))
        self.Steam_recent_games_3.setMaximumSize(QSize(16777215, 242))
        self.Steam_recent_games_3.setStyleSheet(u"")
        self.Steam_recent_games_3.setFrameShape(QFrame.NoFrame)
        self.Steam_recent_games_3.setFrameShadow(QFrame.Sunken)
        self.Steam_recent_games_3.setLineWidth(2)
        self.Steam_recent_games_3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.Steam_recent_games_3.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Steam_recent_games_3.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.Steam_recent_games_3.setWidgetResizable(True)
        self.Steam_recent_games_6 = QWidget()
        self.Steam_recent_games_6.setObjectName(u"Steam_recent_games_6")
        self.Steam_recent_games_6.setEnabled(True)
        self.Steam_recent_games_6.setGeometry(QRect(0, 0, 1622, 228))
        sizePolicy3.setHeightForWidth(self.Steam_recent_games_6.sizePolicy().hasHeightForWidth())
        self.Steam_recent_games_6.setSizePolicy(sizePolicy3)
        self.Steam_recent_games_6.setMinimumSize(QSize(0, 0))
        self.Steam_recent_games_6.setMaximumSize(QSize(16777215, 238))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette5.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush5)
        palette5.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.Accent, brush6)
        self.Steam_recent_games_6.setPalette(palette5)
        self.Steam_recent_games_6.setStyleSheet(u"")
        self.horizontalLayout_10 = QHBoxLayout(self.Steam_recent_games_6)
        self.horizontalLayout_10.setSpacing(8)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.label_38 = QLabel(self.Steam_recent_games_6)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setMinimumSize(QSize(155, 225))
        self.label_38.setMaximumSize(QSize(155, 225))
        self.label_38.setBaseSize(QSize(155, 225))
        self.label_38.setStyleSheet(u"background-image: url(:/covers/resources/covers/ghost_of_tsushima.png);")
        self.label_38.setPixmap(QPixmap(u":/covers/resources/covers/ghost_of_tsushima.png"))
        self.label_38.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.label_38)

        self.label_39 = QLabel(self.Steam_recent_games_6)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setMinimumSize(QSize(155, 225))
        self.label_39.setMaximumSize(QSize(155, 225))
        self.label_39.setBaseSize(QSize(155, 225))
        self.label_39.setStyleSheet(u"image: url(:/covers/resources/covers/doom.png);")
        self.label_39.setPixmap(QPixmap(u":/covers/resources/covers/doom.png"))
        self.label_39.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.label_39)

        self.label_40 = QLabel(self.Steam_recent_games_6)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setMinimumSize(QSize(155, 225))
        self.label_40.setMaximumSize(QSize(155, 225))
        self.label_40.setSizeIncrement(QSize(0, 0))
        self.label_40.setBaseSize(QSize(155, 225))
        self.label_40.setStyleSheet(u"background-image: url(:/covers/resources/covers/ghost_of_tsushima.png);")
        self.label_40.setPixmap(QPixmap(u":/covers/resources/covers/ghost_of_tsushima.png"))
        self.label_40.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.label_40)

        self.label_41 = QLabel(self.Steam_recent_games_6)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setMinimumSize(QSize(155, 225))
        self.label_41.setMaximumSize(QSize(155, 225))
        self.label_41.setBaseSize(QSize(155, 225))
        self.label_41.setStyleSheet(u"image: url(:/covers/resources/covers/doom.png);")
        self.label_41.setPixmap(QPixmap(u":/covers/resources/covers/doom.png"))
        self.label_41.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.label_41)

        self.label_42 = QLabel(self.Steam_recent_games_6)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setMinimumSize(QSize(155, 225))
        self.label_42.setMaximumSize(QSize(155, 225))
        self.label_42.setBaseSize(QSize(155, 225))
        self.label_42.setStyleSheet(u"image: url(:/covers/resources/covers/doom.png);")
        self.label_42.setPixmap(QPixmap(u":/covers/resources/covers/doom.png"))
        self.label_42.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.label_42)

        self.label_43 = QLabel(self.Steam_recent_games_6)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setMinimumSize(QSize(155, 225))
        self.label_43.setMaximumSize(QSize(155, 225))
        self.label_43.setSizeIncrement(QSize(0, 0))
        self.label_43.setBaseSize(QSize(155, 225))
        self.label_43.setStyleSheet(u"background-image: url(:/covers/resources/covers/ghost_of_tsushima.png);")
        self.label_43.setPixmap(QPixmap(u":/covers/resources/covers/ghost_of_tsushima.png"))
        self.label_43.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.label_43)

        self.label_44 = QLabel(self.Steam_recent_games_6)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setMinimumSize(QSize(155, 225))
        self.label_44.setMaximumSize(QSize(155, 225))
        self.label_44.setBaseSize(QSize(155, 225))
        self.label_44.setStyleSheet(u"image: url(:/covers/resources/covers/doom.png);")
        self.label_44.setPixmap(QPixmap(u":/covers/resources/covers/doom.png"))
        self.label_44.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.label_44)

        self.label_45 = QLabel(self.Steam_recent_games_6)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setMinimumSize(QSize(155, 225))
        self.label_45.setMaximumSize(QSize(155, 225))
        self.label_45.setSizeIncrement(QSize(0, 0))
        self.label_45.setBaseSize(QSize(155, 225))
        self.label_45.setStyleSheet(u"background-image: url(:/covers/resources/covers/ghost_of_tsushima.png);")
        self.label_45.setPixmap(QPixmap(u":/covers/resources/covers/ghost_of_tsushima.png"))
        self.label_45.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.label_45)

        self.label_46 = QLabel(self.Steam_recent_games_6)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setMinimumSize(QSize(155, 225))
        self.label_46.setMaximumSize(QSize(155, 225))
        self.label_46.setBaseSize(QSize(155, 225))
        self.label_46.setStyleSheet(u"background-image: url(:/covers/resources/covers/ghost_of_tsushima.png);")
        self.label_46.setPixmap(QPixmap(u":/covers/resources/covers/ghost_of_tsushima.png"))
        self.label_46.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.label_46)

        self.label_47 = QLabel(self.Steam_recent_games_6)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setMinimumSize(QSize(155, 225))
        self.label_47.setMaximumSize(QSize(155, 225))
        self.label_47.setBaseSize(QSize(155, 225))
        self.label_47.setStyleSheet(u"image: url(:/covers/resources/covers/doom.png);")
        self.label_47.setPixmap(QPixmap(u":/covers/resources/covers/doom.png"))
        self.label_47.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.label_47)

        self.Steam_recent_games_3.setWidget(self.Steam_recent_games_6)

        self.verticalLayout_3.addWidget(self.Steam_recent_games_3)


        self.verticalLayout.addWidget(self.widget_4)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.horizontalLayout_5.addWidget(self.scrollArea)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Games Vault", None))
        self.label_2.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Steam", None))
        self.connect_steam.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Last Played", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"All games", None))
        self.label_38.setText("")
        self.label_39.setText("")
        self.label_40.setText("")
        self.label_41.setText("")
        self.label_42.setText("")
        self.label_43.setText("")
        self.label_44.setText("")
        self.label_45.setText("")
        self.label_46.setText("")
        self.label_47.setText("")
    # retranslateUi

