# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QGridLayout,
    QHBoxLayout, QLabel, QMainWindow, QPushButton,
    QScrollArea, QSizePolicy, QTabWidget, QVBoxLayout,
    QWidget)
import rc_resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1200, 600)
        MainWindow.setMaximumSize(QSize(16777215, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(18, 18, 18, 200))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setWindowOpacity(0.950000000000000)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(25, 25))
        self.centralwidget.setBaseSize(QSize(0, 0))
        self.horizontalLayout_7 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        font = QFont()
        font.setPointSize(13)
        self.tabWidget.setFont(font)
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.Last_played = QWidget()
        self.Last_played.setObjectName(u"Last_played")
        font1 = QFont()
        font1.setPointSize(12)
        self.Last_played.setFont(font1)
        self.verticalLayout_5 = QVBoxLayout(self.Last_played)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 5, 0, 0)
        self.scrollArea = QScrollArea(self.Last_played)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1194, 557))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        palette1 = QPalette()
        brush1 = QBrush(QColor(4, 12, 6, 200))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.scrollAreaWidgetContents.setPalette(palette1)
        self.verticalLayout = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 25, 0, 0)
        self.widget = QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName(u"widget")
        self.widget.setMinimumSize(QSize(0, 375))
        self.widget.setMaximumSize(QSize(16777215, 375))
        self.widget.setBaseSize(QSize(0, 375))
        self.verticalLayout_2 = QVBoxLayout(self.widget)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.widget_2 = QWidget(self.widget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setMaximumSize(QSize(500, 50))
        self.horizontalLayout_2 = QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.widget_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy1)
        self.label_2.setMinimumSize(QSize(25, 25))
        self.label_2.setMaximumSize(QSize(50, 50))
        self.label_2.setSizeIncrement(QSize(0, 0))
        self.label_2.setBaseSize(QSize(25, 25))
        self.label_2.setStyleSheet(u"image: url(:/icons/resources/icons/steam-icon.png);")
        self.label_2.setPixmap(QPixmap(u":/icons/resources/icons/steam-icon.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setMargin(0)

        self.horizontalLayout_2.addWidget(self.label_2)

        self.label = QLabel(self.widget_2)
        self.label.setObjectName(u"label")
        self.label.setEnabled(False)
        self.label.setMinimumSize(QSize(25, 25))
        self.label.setMaximumSize(QSize(100, 50))
        self.label.setBaseSize(QSize(25, 25))
        font2 = QFont()
        font2.setPointSize(24)
        font2.setStyleStrategy(QFont.PreferDefault)
        self.label.setFont(font2)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.horizontalLayout_2.addWidget(self.label)

        self.connect_steam = QPushButton(self.widget_2)
        self.connect_steam.setObjectName(u"connect_steam")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.connect_steam.sizePolicy().hasHeightForWidth())
        self.connect_steam.setSizePolicy(sizePolicy2)
        self.connect_steam.setMaximumSize(QSize(100, 50))
        palette2 = QPalette()
        brush2 = QBrush(QColor(66, 66, 66, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        self.connect_steam.setPalette(palette2)
        font3 = QFont()
        font3.setFamilies([u"Inter"])
        font3.setPointSize(12)
        self.connect_steam.setFont(font3)
        self.connect_steam.setCursor(QCursor(Qt.PointingHandCursor))
        self.connect_steam.setFlat(False)

        self.horizontalLayout_2.addWidget(self.connect_steam)

        self.change_steam_directory = QPushButton(self.widget_2)
        self.change_steam_directory.setObjectName(u"change_steam_directory")
        sizePolicy2.setHeightForWidth(self.change_steam_directory.sizePolicy().hasHeightForWidth())
        self.change_steam_directory.setSizePolicy(sizePolicy2)
        self.change_steam_directory.setMaximumSize(QSize(175, 50))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        self.change_steam_directory.setPalette(palette3)
        self.change_steam_directory.setFont(font3)
        self.change_steam_directory.setCursor(QCursor(Qt.PointingHandCursor))
        self.change_steam_directory.setText(u"\ud83d\udcc1 Change directory")
        self.change_steam_directory.setFlat(False)

        self.horizontalLayout_2.addWidget(self.change_steam_directory)


        self.verticalLayout_2.addWidget(self.widget_2)

        self.widget_3 = QWidget(self.widget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setMaximumSize(QSize(16777215, 50))
        self.horizontalLayout = QHBoxLayout(self.widget_3)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_6 = QLabel(self.widget_3)
        self.label_6.setObjectName(u"label_6")
        font4 = QFont()
        font4.setPointSize(18)
        self.label_6.setFont(font4)
        self.label_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.label_6)


        self.verticalLayout_2.addWidget(self.widget_3)

        self.widget_5 = QWidget(self.widget)
        self.widget_5.setObjectName(u"widget_5")
        self.verticalLayout_4 = QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(75, 0, 75, 0)
        self.Steam_recent_games_2 = QScrollArea(self.widget_5)
        self.Steam_recent_games_2.setObjectName(u"Steam_recent_games_2")
        self.Steam_recent_games_2.setEnabled(True)
        self.Steam_recent_games_2.setMinimumSize(QSize(0, 0))
        self.Steam_recent_games_2.setMaximumSize(QSize(16777215, 242))
        self.Steam_recent_games_2.setStyleSheet(u"")
        self.Steam_recent_games_2.setFrameShape(QFrame.NoFrame)
        self.Steam_recent_games_2.setFrameShadow(QFrame.Sunken)
        self.Steam_recent_games_2.setLineWidth(2)
        self.Steam_recent_games_2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.Steam_recent_games_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Steam_recent_games_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.Steam_recent_games_2.setWidgetResizable(True)
        self.Steam_recent_games = QWidget()
        self.Steam_recent_games.setObjectName(u"Steam_recent_games")
        self.Steam_recent_games.setEnabled(True)
        self.Steam_recent_games.setGeometry(QRect(0, 0, 1024, 238))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.Steam_recent_games.sizePolicy().hasHeightForWidth())
        self.Steam_recent_games.setSizePolicy(sizePolicy3)
        self.Steam_recent_games.setMinimumSize(QSize(0, 0))
        self.Steam_recent_games.setMaximumSize(QSize(16777215, 238))
        palette4 = QPalette()
        brush3 = QBrush(QColor(4, 12, 6, 100))
        brush3.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(4, 12, 6, 225))
        brush4.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush4)
        brush5 = QBrush(QColor(105, 105, 105, 200))
        brush5.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        brush6 = QBrush(QColor(74, 84, 89, 225))
        brush6.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Shadow, brush5)
        palette4.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Accent, brush6)
        self.Steam_recent_games.setPalette(palette4)
        self.Steam_recent_games.setStyleSheet(u"")
        self.horizontalLayout_3 = QHBoxLayout(self.Steam_recent_games)
        self.horizontalLayout_3.setSpacing(8)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 10)
        self.Steam_recent_games_2.setWidget(self.Steam_recent_games)

        self.verticalLayout_4.addWidget(self.Steam_recent_games_2)


        self.verticalLayout_2.addWidget(self.widget_5)


        self.verticalLayout.addWidget(self.widget)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_5.addWidget(self.scrollArea)

        self.tabWidget.addTab(self.Last_played, "")
        self.All_games = QWidget()
        self.All_games.setObjectName(u"All_games")
        self.verticalLayout_6 = QVBoxLayout(self.All_games)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 5, 0, 0)
        self.scrollArea_2 = QScrollArea(self.All_games)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 1194, 557))
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.scrollAreaWidgetContents_2.setPalette(palette5)
        self.verticalLayout_7 = QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 25, 0, 0)
        self.widget_11 = QWidget(self.scrollAreaWidgetContents_2)
        self.widget_11.setObjectName(u"widget_11")
        self.widget_11.setMinimumSize(QSize(0, 350))
        self.widget_11.setMaximumSize(QSize(16777215, 16777215))
        self.widget_11.setBaseSize(QSize(0, 375))
        self.verticalLayout_10 = QVBoxLayout(self.widget_11)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.widget_12 = QWidget(self.widget_11)
        self.widget_12.setObjectName(u"widget_12")
        self.widget_12.setMaximumSize(QSize(16777215, 50))
        self.horizontalLayout_11 = QHBoxLayout(self.widget_12)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.label_48 = QLabel(self.widget_12)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setFont(font4)
        self.label_48.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_48.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_11.addWidget(self.label_48)


        self.verticalLayout_10.addWidget(self.widget_12)

        self.Steam_recent_games_7 = QScrollArea(self.widget_11)
        self.Steam_recent_games_7.setObjectName(u"Steam_recent_games_7")
        self.Steam_recent_games_7.setEnabled(True)
        self.Steam_recent_games_7.setMinimumSize(QSize(0, 0))
        self.Steam_recent_games_7.setMaximumSize(QSize(16777215, 16777215))
        self.Steam_recent_games_7.setStyleSheet(u"")
        self.Steam_recent_games_7.setFrameShape(QFrame.NoFrame)
        self.Steam_recent_games_7.setFrameShadow(QFrame.Sunken)
        self.Steam_recent_games_7.setLineWidth(2)
        self.Steam_recent_games_7.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Steam_recent_games_7.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Steam_recent_games_7.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.Steam_recent_games_7.setWidgetResizable(True)
        self.Steam_recent_games_8 = QWidget()
        self.Steam_recent_games_8.setObjectName(u"Steam_recent_games_8")
        self.Steam_recent_games_8.setEnabled(True)
        self.Steam_recent_games_8.setGeometry(QRect(0, 0, 1194, 490))
        sizePolicy3.setHeightForWidth(self.Steam_recent_games_8.sizePolicy().hasHeightForWidth())
        self.Steam_recent_games_8.setSizePolicy(sizePolicy3)
        self.Steam_recent_games_8.setMinimumSize(QSize(0, 0))
        self.Steam_recent_games_8.setMaximumSize(QSize(16777215, 16777215))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette6.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Shadow, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.Accent, brush6)
        self.Steam_recent_games_8.setPalette(palette6)
        self.Steam_recent_games_8.setStyleSheet(u"")
        self.gridLayout = QGridLayout(self.Steam_recent_games_8)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.Steam_recent_games_7.setWidget(self.Steam_recent_games_8)

        self.verticalLayout_10.addWidget(self.Steam_recent_games_7)


        self.verticalLayout_7.addWidget(self.widget_11)

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        self.verticalLayout_6.addWidget(self.scrollArea_2)

        self.tabWidget.addTab(self.All_games, "")

        self.horizontalLayout_7.addWidget(self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Games Vault", None))
        self.label_2.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Steam", None))
        self.connect_steam.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Last Played", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Last_played), QCoreApplication.translate("MainWindow", u"Last Played", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"All games", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.All_games), QCoreApplication.translate("MainWindow", u"All Games", None))
    # retranslateUi

