# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QHBoxLayout,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QScrollArea, QSizePolicy, QSlider, QSpacerItem,
    QTabWidget, QVBoxLayout, QWidget)
import rc_resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1200, 600)
        MainWindow.setMaximumSize(QSize(16777215, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(18, 18, 18, 200))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setWindowOpacity(0.950000000000000)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(25, 25))
        self.centralwidget.setBaseSize(QSize(0, 0))
        self.horizontalLayout_7 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        palette1 = QPalette()
        brush1 = QBrush(QColor(255, 255, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        brush2 = QBrush(QColor(0, 0, 0, 200))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.tabWidget.setPalette(palette1)
        font = QFont()
        font.setPointSize(14)
        font.setStyleStrategy(QFont.PreferDefault)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(u"")
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.Last_played = QWidget()
        self.Last_played.setObjectName(u"Last_played")
        palette2 = QPalette()
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush3)
        brush4 = QBrush(QColor(0, 0, 0, 225))
        brush4.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Link, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Accent, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Link, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Accent, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Link, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Accent, brush3)
        self.Last_played.setPalette(palette2)
        font1 = QFont()
        font1.setPointSize(12)
        font1.setStyleStrategy(QFont.PreferDefault)
        self.Last_played.setFont(font1)
        self.verticalLayout_5 = QVBoxLayout(self.Last_played)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.scrollArea = QScrollArea(self.Last_played)
        self.scrollArea.setObjectName(u"scrollArea")
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        self.scrollArea.setPalette(palette3)
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1198, 560))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        palette4 = QPalette()
        brush5 = QBrush(QColor(12, 16, 8, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        self.scrollAreaWidgetContents.setPalette(palette4)
        self.verticalLayout = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.widget = QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName(u"widget")
        self.widget.setMinimumSize(QSize(0, 375))
        self.widget.setMaximumSize(QSize(16777215, 16777215))
        self.widget.setBaseSize(QSize(0, 0))
        self.verticalLayout_2 = QVBoxLayout(self.widget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.navbar = QWidget(self.widget)
        self.navbar.setObjectName(u"navbar")
        self.navbar.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalLayout = QHBoxLayout(self.navbar)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 5, 0, 10)
        self.widget_3 = QWidget(self.navbar)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setMinimumSize(QSize(0, 70))
        self.widget_3.setMaximumSize(QSize(415, 70))
        self.widget_3.setStyleSheet(u"")
        self.horizontalLayout_3 = QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(15, 0, 0, 0)
        self.user_avatar = QLabel(self.widget_3)
        self.user_avatar.setObjectName(u"user_avatar")
        self.user_avatar.setMinimumSize(QSize(0, 64))
        self.user_avatar.setMaximumSize(QSize(64, 64))
        self.user_avatar.setStyleSheet(u"")
        self.user_avatar.setPixmap(QPixmap(u":/icons/resources/icons/user_icon.png"))
        self.user_avatar.setScaledContents(True)
        self.user_avatar.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.user_avatar.setMargin(0)
        self.user_avatar.setIndent(-1)

        self.horizontalLayout_3.addWidget(self.user_avatar)

        self.widget_9 = QWidget(self.widget_3)
        self.widget_9.setObjectName(u"widget_9")
        self.widget_9.setMinimumSize(QSize(0, 0))
        self.widget_9.setStyleSheet(u"")
        self.verticalLayout_17 = QVBoxLayout(self.widget_9)
        self.verticalLayout_17.setSpacing(25)
        self.verticalLayout_17.setObjectName(u"verticalLayout_17")
        self.verticalLayout_17.setContentsMargins(3, 0, -1, 25)
        self.user_display_name = QLabel(self.widget_9)
        self.user_display_name.setObjectName(u"user_display_name")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.user_display_name.sizePolicy().hasHeightForWidth())
        self.user_display_name.setSizePolicy(sizePolicy1)
        self.user_display_name.setMinimumSize(QSize(0, 40))
        self.user_display_name.setMaximumSize(QSize(16777215, 16777215))
        font2 = QFont()
        font2.setPointSize(20)
        font2.setBold(False)
        font2.setItalic(False)
        font2.setStyleStrategy(QFont.PreferDefault)
        self.user_display_name.setFont(font2)
        self.user_display_name.setCursor(QCursor(Qt.ArrowCursor))
        self.user_display_name.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.user_display_name.setScaledContents(False)
        self.user_display_name.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.user_display_name.setWordWrap(False)
        self.user_display_name.setMargin(0)
        self.user_display_name.setIndent(0)

        self.verticalLayout_17.addWidget(self.user_display_name)

        self.user_total_playtime = QLabel(self.widget_9)
        self.user_total_playtime.setObjectName(u"user_total_playtime")
        self.user_total_playtime.setMinimumSize(QSize(0, 35))
        self.user_total_playtime.setStyleSheet(u"color: rgb(0, 255, 255);")
        self.user_total_playtime.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.verticalLayout_17.addWidget(self.user_total_playtime)

        self.recent_games_refresh_info = QLabel(self.widget_9)
        self.recent_games_refresh_info.setObjectName(u"recent_games_refresh_info")
        self.recent_games_refresh_info.setMinimumSize(QSize(0, 20))
        self.recent_games_refresh_info.setStyleSheet(u"color: darkgrey; ")
        self.recent_games_refresh_info.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.verticalLayout_17.addWidget(self.recent_games_refresh_info)


        self.horizontalLayout_3.addWidget(self.widget_9)


        self.horizontalLayout.addWidget(self.widget_3)

        self.change_steam_id_container = QWidget(self.navbar)
        self.change_steam_id_container.setObjectName(u"change_steam_id_container")
        self.change_steam_id_container.setMinimumSize(QSize(0, 64))
        self.change_steam_id_container.setMaximumSize(QSize(415, 64))
        self.change_steam_id_container.setFont(font1)
        self.horizontalLayout_12 = QHBoxLayout(self.change_steam_id_container)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")

        self.horizontalLayout.addWidget(self.change_steam_id_container)

        self.widget_5 = QWidget(self.navbar)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setMinimumSize(QSize(0, 64))
        self.widget_5.setMaximumSize(QSize(415, 64))
        self.horizontalLayout_13 = QHBoxLayout(self.widget_5)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")

        self.horizontalLayout.addWidget(self.widget_5)


        self.verticalLayout_2.addWidget(self.navbar)

        self.Recent_games_container = QWidget(self.widget)
        self.Recent_games_container.setObjectName(u"Recent_games_container")
        self.Recent_games_container.setMaximumSize(QSize(16777215, 16777215))
        self.verticalLayout_4 = QVBoxLayout(self.Recent_games_container)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 5, 0, 0)
        self.Steam_recent_games_2 = QScrollArea(self.Recent_games_container)
        self.Steam_recent_games_2.setObjectName(u"Steam_recent_games_2")
        self.Steam_recent_games_2.setEnabled(True)
        sizePolicy.setHeightForWidth(self.Steam_recent_games_2.sizePolicy().hasHeightForWidth())
        self.Steam_recent_games_2.setSizePolicy(sizePolicy)
        self.Steam_recent_games_2.setMinimumSize(QSize(0, 0))
        self.Steam_recent_games_2.setMaximumSize(QSize(16777215, 16777215))
        palette5 = QPalette()
        brush6 = QBrush(QColor(12, 16, 8, 0))
        brush6.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush6)
        self.Steam_recent_games_2.setPalette(palette5)
        self.Steam_recent_games_2.setStyleSheet(u"")
        self.Steam_recent_games_2.setFrameShape(QFrame.NoFrame)
        self.Steam_recent_games_2.setFrameShadow(QFrame.Sunken)
        self.Steam_recent_games_2.setLineWidth(2)
        self.Steam_recent_games_2.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Steam_recent_games_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Steam_recent_games_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.Steam_recent_games_2.setWidgetResizable(True)
        self.Steam_recent_games_alignment = QWidget()
        self.Steam_recent_games_alignment.setObjectName(u"Steam_recent_games_alignment")
        self.Steam_recent_games_alignment.setEnabled(True)
        self.Steam_recent_games_alignment.setGeometry(QRect(0, 0, 1198, 280))
        sizePolicy1.setHeightForWidth(self.Steam_recent_games_alignment.sizePolicy().hasHeightForWidth())
        self.Steam_recent_games_alignment.setSizePolicy(sizePolicy1)
        self.Steam_recent_games_alignment.setMinimumSize(QSize(0, 0))
        self.Steam_recent_games_alignment.setMaximumSize(QSize(16777215, 16777215))
        palette6 = QPalette()
        brush7 = QBrush(QColor(4, 12, 6, 100))
        brush7.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush7)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush5)
        brush8 = QBrush(QColor(105, 105, 105, 200))
        brush8.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Shadow, brush8)
        brush9 = QBrush(QColor(74, 84, 89, 225))
        brush9.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Accent, brush9)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette6.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.Shadow, brush8)
        palette6.setBrush(QPalette.Disabled, QPalette.Accent, brush9)
        self.Steam_recent_games_alignment.setPalette(palette6)
        self.Steam_recent_games_alignment.setAutoFillBackground(True)
        self.Steam_recent_games_alignment.setStyleSheet(u"")
        self.verticalLayout_3 = QVBoxLayout(self.Steam_recent_games_alignment)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.Steam_recent_games = QWidget(self.Steam_recent_games_alignment)
        self.Steam_recent_games.setObjectName(u"Steam_recent_games")

        self.verticalLayout_3.addWidget(self.Steam_recent_games)

        self.Steam_recent_games_2.setWidget(self.Steam_recent_games_alignment)

        self.verticalLayout_4.addWidget(self.Steam_recent_games_2)


        self.verticalLayout_2.addWidget(self.Recent_games_container)


        self.verticalLayout.addWidget(self.widget)

        self.widget_7 = QWidget(self.scrollAreaWidgetContents)
        self.widget_7.setObjectName(u"widget_7")
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QSize(0, 175))
        self.widget_7.setMaximumSize(QSize(16777215, 300))
        self.verticalLayout_9 = QVBoxLayout(self.widget_7)
        self.verticalLayout_9.setSpacing(15)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 15)
        self.scrollArea_3 = QScrollArea(self.widget_7)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setMinimumSize(QSize(0, 175))
        self.scrollArea_3.setMaximumSize(QSize(16777215, 300))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 1196, 173))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        self.scrollAreaWidgetContents_3.setPalette(palette7)
        self.verticalLayout_8 = QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.widget_4 = QWidget(self.scrollAreaWidgetContents_3)
        self.widget_4.setObjectName(u"widget_4")
        self.horizontalLayout_5 = QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.widget_2 = QWidget(self.widget_4)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setMinimumSize(QSize(700, 0))
        self.widget_2.setMaximumSize(QSize(700, 50))
        self.horizontalLayout_2 = QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.widget_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy2)
        self.label_2.setMinimumSize(QSize(25, 25))
        self.label_2.setMaximumSize(QSize(50, 50))
        self.label_2.setSizeIncrement(QSize(0, 0))
        self.label_2.setBaseSize(QSize(25, 25))
        self.label_2.setStyleSheet(u"")
        self.label_2.setPixmap(QPixmap(u":/icons/resources/icons/steam-icon.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setMargin(0)

        self.horizontalLayout_2.addWidget(self.label_2)

        self.label = QLabel(self.widget_2)
        self.label.setObjectName(u"label")
        self.label.setEnabled(False)
        self.label.setMinimumSize(QSize(25, 25))
        self.label.setMaximumSize(QSize(175, 50))
        self.label.setBaseSize(QSize(25, 25))
        font3 = QFont()
        font3.setPointSize(24)
        font3.setStyleStrategy(QFont.PreferDefault)
        self.label.setFont(font3)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label.setIndent(-1)

        self.horizontalLayout_2.addWidget(self.label)

        self.find_steam_directory = QPushButton(self.widget_2)
        self.find_steam_directory.setObjectName(u"find_steam_directory")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.find_steam_directory.sizePolicy().hasHeightForWidth())
        self.find_steam_directory.setSizePolicy(sizePolicy3)
        self.find_steam_directory.setMaximumSize(QSize(175, 50))
        palette8 = QPalette()
        brush10 = QBrush(QColor(66, 66, 66, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush10)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush10)
        self.find_steam_directory.setPalette(palette8)
        font4 = QFont()
        font4.setFamilies([u"Inter"])
        font4.setPointSize(12)
        font4.setStyleStrategy(QFont.PreferDefault)
        self.find_steam_directory.setFont(font4)
        self.find_steam_directory.setCursor(QCursor(Qt.PointingHandCursor))
        self.find_steam_directory.setText(u"\ud83d\udcc1 Find directory")
        self.find_steam_directory.setFlat(False)

        self.horizontalLayout_2.addWidget(self.find_steam_directory)

        self.steam_dir_info = QLabel(self.widget_2)
        self.steam_dir_info.setObjectName(u"steam_dir_info")
        self.steam_dir_info.setMaximumSize(QSize(200, 16777215))
        font5 = QFont()
        font5.setPointSize(13)
        font5.setStyleStrategy(QFont.PreferDefault)
        self.steam_dir_info.setFont(font5)
        self.steam_dir_info.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.steam_dir_info.setTextFormat(Qt.MarkdownText)
        self.steam_dir_info.setScaledContents(False)
        self.steam_dir_info.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.steam_dir_info.setWordWrap(False)

        self.horizontalLayout_2.addWidget(self.steam_dir_info)


        self.horizontalLayout_5.addWidget(self.widget_2)


        self.verticalLayout_8.addWidget(self.widget_4)

        self.widget_8 = QWidget(self.scrollAreaWidgetContents_3)
        self.widget_8.setObjectName(u"widget_8")
        self.horizontalLayout_6 = QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.widget_6 = QWidget(self.widget_8)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setMinimumSize(QSize(700, 0))
        self.widget_6.setMaximumSize(QSize(700, 50))
        self.horizontalLayout_4 = QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.widget_6)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy2)
        self.label_3.setMinimumSize(QSize(25, 25))
        self.label_3.setMaximumSize(QSize(50, 50))
        self.label_3.setSizeIncrement(QSize(0, 0))
        self.label_3.setBaseSize(QSize(25, 25))
        self.label_3.setStyleSheet(u"")
        self.label_3.setPixmap(QPixmap(u":/icons/resources/icons/epic_games_icon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setMargin(0)

        self.horizontalLayout_4.addWidget(self.label_3)

        self.label_4 = QLabel(self.widget_6)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setEnabled(False)
        self.label_4.setMinimumSize(QSize(25, 25))
        self.label_4.setMaximumSize(QSize(175, 50))
        self.label_4.setBaseSize(QSize(25, 25))
        self.label_4.setFont(font3)
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.horizontalLayout_4.addWidget(self.label_4)

        self.find_epic_games_directory = QPushButton(self.widget_6)
        self.find_epic_games_directory.setObjectName(u"find_epic_games_directory")
        sizePolicy3.setHeightForWidth(self.find_epic_games_directory.sizePolicy().hasHeightForWidth())
        self.find_epic_games_directory.setSizePolicy(sizePolicy3)
        self.find_epic_games_directory.setMaximumSize(QSize(175, 50))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.Button, brush10)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush10)
        self.find_epic_games_directory.setPalette(palette9)
        self.find_epic_games_directory.setFont(font4)
        self.find_epic_games_directory.setCursor(QCursor(Qt.PointingHandCursor))
        self.find_epic_games_directory.setText(u"\ud83d\udcc1 Find directory ")
        self.find_epic_games_directory.setFlat(False)

        self.horizontalLayout_4.addWidget(self.find_epic_games_directory)

        self.epic_dir_info = QLabel(self.widget_6)
        self.epic_dir_info.setObjectName(u"epic_dir_info")
        self.epic_dir_info.setMaximumSize(QSize(200, 16777215))
        self.epic_dir_info.setFont(font5)
        self.epic_dir_info.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.epic_dir_info.setTextFormat(Qt.MarkdownText)
        self.epic_dir_info.setScaledContents(False)
        self.epic_dir_info.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.epic_dir_info.setWordWrap(False)

        self.horizontalLayout_4.addWidget(self.epic_dir_info)


        self.horizontalLayout_6.addWidget(self.widget_6)


        self.verticalLayout_8.addWidget(self.widget_8)

        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)

        self.verticalLayout_9.addWidget(self.scrollArea_3)


        self.verticalLayout.addWidget(self.widget_7)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_5.addWidget(self.scrollArea)

        self.tabWidget.addTab(self.Last_played, "")
        self.Installed_games = QWidget()
        self.Installed_games.setObjectName(u"Installed_games")
        self.verticalLayout_6 = QVBoxLayout(self.Installed_games)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.scrollArea_2 = QScrollArea(self.Installed_games)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 1198, 560))
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        palette10 = QPalette()
        brush11 = QBrush(QColor(4, 12, 6, 200))
        brush11.setStyle(Qt.SolidPattern)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.scrollAreaWidgetContents_2.setPalette(palette10)
        self.verticalLayout_7 = QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 5, 0, 0)
        self.installed_games_container = QWidget(self.scrollAreaWidgetContents_2)
        self.installed_games_container.setObjectName(u"installed_games_container")
        self.installed_games_container.setMinimumSize(QSize(0, 350))
        self.installed_games_container.setMaximumSize(QSize(16777215, 16777215))
        self.installed_games_container.setBaseSize(QSize(0, 375))
        self.verticalLayout_10 = QVBoxLayout(self.installed_games_container)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.widget_12 = QWidget(self.installed_games_container)
        self.widget_12.setObjectName(u"widget_12")
        self.widget_12.setMaximumSize(QSize(16777215, 50))
        self.horizontalLayout_11 = QHBoxLayout(self.widget_12)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.widget_11 = QWidget(self.widget_12)
        self.widget_11.setObjectName(u"widget_11")
        self.horizontalLayout_18 = QHBoxLayout(self.widget_11)
        self.horizontalLayout_18.setSpacing(5)
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.installed_games_quantity = QLabel(self.widget_11)
        self.installed_games_quantity.setObjectName(u"installed_games_quantity")
        self.installed_games_quantity.setMaximumSize(QSize(16777215, 16777215))
        font6 = QFont()
        font6.setPointSize(18)
        font6.setStyleStrategy(QFont.PreferDefault)
        self.installed_games_quantity.setFont(font6)
        self.installed_games_quantity.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.installed_games_quantity.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.installed_games_quantity.setMargin(0)
        self.installed_games_quantity.setIndent(15)

        self.horizontalLayout_18.addWidget(self.installed_games_quantity)

        self.horizontalSpacer_7 = QSpacerItem(50, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_18.addItem(self.horizontalSpacer_7)

        self.open_widget = QPushButton(self.widget_11)
        self.open_widget.setObjectName(u"open_widget")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.open_widget.sizePolicy().hasHeightForWidth())
        self.open_widget.setSizePolicy(sizePolicy4)
        self.open_widget.setCursor(QCursor(Qt.PointingHandCursor))
        self.open_widget.setStyleSheet(u"color: rgb(0, 255,0);")

        self.horizontalLayout_18.addWidget(self.open_widget)


        self.horizontalLayout_11.addWidget(self.widget_11)

        self.width_slider_container = QWidget(self.widget_12)
        self.width_slider_container.setObjectName(u"width_slider_container")
        self.width_slider_container.setMaximumSize(QSize(415, 16777215))
        self.horizontalLayout_10 = QHBoxLayout(self.width_slider_container)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(-1, 4, -1, 0)
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_10.addItem(self.horizontalSpacer_2)

        self.set_img_cover_width = QSlider(self.width_slider_container)
        self.set_img_cover_width.setObjectName(u"set_img_cover_width")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.set_img_cover_width.sizePolicy().hasHeightForWidth())
        self.set_img_cover_width.setSizePolicy(sizePolicy5)
        self.set_img_cover_width.setMinimumSize(QSize(0, 0))
        self.set_img_cover_width.setMaximumSize(QSize(16777215, 16777215))
        palette11 = QPalette()
        brush12 = QBrush(QColor(0, 255, 0, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette11.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette11.setBrush(QPalette.Active, QPalette.Shadow, brush12)
        palette11.setBrush(QPalette.Active, QPalette.Link, brush12)
        palette11.setBrush(QPalette.Active, QPalette.Accent, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.Shadow, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.Link, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.Accent, brush12)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        palette11.setBrush(QPalette.Disabled, QPalette.Shadow, brush12)
        palette11.setBrush(QPalette.Disabled, QPalette.Link, brush12)
        palette11.setBrush(QPalette.Disabled, QPalette.Accent, brush12)
        self.set_img_cover_width.setPalette(palette11)
        self.set_img_cover_width.setStyleSheet(u"")
        self.set_img_cover_width.setMinimum(50)
        self.set_img_cover_width.setMaximum(264)
        self.set_img_cover_width.setValue(140)
        self.set_img_cover_width.setOrientation(Qt.Horizontal)

        self.horizontalLayout_10.addWidget(self.set_img_cover_width)

        self.img_cover_width_info = QLabel(self.width_slider_container)
        self.img_cover_width_info.setObjectName(u"img_cover_width_info")
        self.img_cover_width_info.setMaximumSize(QSize(16777215, 35))
        self.img_cover_width_info.setBaseSize(QSize(0, 2))
        self.img_cover_width_info.setFont(font1)
        self.img_cover_width_info.setStyleSheet(u"color: rgb(0, 255, 0);\n"
"margin-top: 0.5px;\n"
"")
        self.img_cover_width_info.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.img_cover_width_info.setMargin(0)

        self.horizontalLayout_10.addWidget(self.img_cover_width_info)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_10.addItem(self.horizontalSpacer_3)


        self.horizontalLayout_11.addWidget(self.width_slider_container)

        self.search_widget_container = QWidget(self.widget_12)
        self.search_widget_container.setObjectName(u"search_widget_container")
        sizePolicy1.setHeightForWidth(self.search_widget_container.sizePolicy().hasHeightForWidth())
        self.search_widget_container.setSizePolicy(sizePolicy1)
        self.search_widget_container.setMaximumSize(QSize(415, 16777215))
        self.search_widget_container.setLayoutDirection(Qt.LeftToRight)
        self.horizontalLayout_8 = QHBoxLayout(self.search_widget_container)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 15, 0)
        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_8.addItem(self.horizontalSpacer)

        self.widget_10 = QWidget(self.search_widget_container)
        self.widget_10.setObjectName(u"widget_10")
        sizePolicy5.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy5)
        self.widget_10.setStyleSheet(u"border: 2px solid white;;\n"
"border-radius: 15px;\n"
"background-color: rgba(0, 0, 0, 0);")
        self.horizontalLayout_9 = QHBoxLayout(self.widget_10)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(10, 2, 10, 2)
        self.label_5 = QLabel(self.widget_10)
        self.label_5.setObjectName(u"label_5")
        sizePolicy1.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy1)
        self.label_5.setMaximumSize(QSize(24, 24))
        palette12 = QPalette()
        brush13 = QBrush(QColor(0, 0, 0, 0))
        brush13.setStyle(Qt.SolidPattern)
        palette12.setBrush(QPalette.Active, QPalette.Button, brush13)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush13)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush13)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush13)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush13)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush13)
        self.label_5.setPalette(palette12)
        font7 = QFont()
        font7.setPointSize(9)
        font7.setStyleStrategy(QFont.PreferDefault)
        self.label_5.setFont(font7)
        self.label_5.setStyleSheet(u"border: 0;")
        self.label_5.setPixmap(QPixmap(u":/icons/resources/icons/search-white.png"))
        self.label_5.setScaledContents(True)

        self.horizontalLayout_9.addWidget(self.label_5)

        self.search_games = QLineEdit(self.widget_10)
        self.search_games.setObjectName(u"search_games")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.search_games.sizePolicy().hasHeightForWidth())
        self.search_games.setSizePolicy(sizePolicy6)
        self.search_games.setMaximumSize(QSize(16777215, 16777215))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.Button, brush13)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush13)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush13)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush13)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush13)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush13)
        self.search_games.setPalette(palette13)
        font8 = QFont()
        font8.setPointSize(15)
        font8.setBold(False)
        font8.setKerning(True)
        font8.setStyleStrategy(QFont.PreferDefault)
        self.search_games.setFont(font8)
        self.search_games.setAcceptDrops(True)
        self.search_games.setLayoutDirection(Qt.LeftToRight)
        self.search_games.setStyleSheet(u"border: 0; margin-bottom: 3px;")
        self.search_games.setFrame(False)
        self.search_games.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.search_games.setDragEnabled(False)

        self.horizontalLayout_9.addWidget(self.search_games)


        self.horizontalLayout_8.addWidget(self.widget_10)


        self.horizontalLayout_11.addWidget(self.search_widget_container)


        self.verticalLayout_10.addWidget(self.widget_12)

        self.Steam_recent_games_7 = QScrollArea(self.installed_games_container)
        self.Steam_recent_games_7.setObjectName(u"Steam_recent_games_7")
        self.Steam_recent_games_7.setEnabled(True)
        self.Steam_recent_games_7.setMinimumSize(QSize(0, 0))
        self.Steam_recent_games_7.setMaximumSize(QSize(16777215, 16777215))
        self.Steam_recent_games_7.setStyleSheet(u"")
        self.Steam_recent_games_7.setFrameShape(QFrame.NoFrame)
        self.Steam_recent_games_7.setFrameShadow(QFrame.Sunken)
        self.Steam_recent_games_7.setLineWidth(2)
        self.Steam_recent_games_7.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Steam_recent_games_7.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Steam_recent_games_7.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.Steam_recent_games_7.setWidgetResizable(True)
        self.Installed_games_content = QWidget()
        self.Installed_games_content.setObjectName(u"Installed_games_content")
        self.Installed_games_content.setEnabled(True)
        self.Installed_games_content.setGeometry(QRect(0, 0, 1198, 509))
        sizePolicy1.setHeightForWidth(self.Installed_games_content.sizePolicy().hasHeightForWidth())
        self.Installed_games_content.setSizePolicy(sizePolicy1)
        self.Installed_games_content.setMinimumSize(QSize(0, 0))
        self.Installed_games_content.setMaximumSize(QSize(16777215, 16777215))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.Base, brush7)
        brush14 = QBrush(QColor(4, 12, 6, 225))
        brush14.setStyle(Qt.SolidPattern)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette14.setBrush(QPalette.Active, QPalette.Shadow, brush8)
        palette14.setBrush(QPalette.Active, QPalette.Accent, brush9)
        palette14.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette14.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette14.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        palette14.setBrush(QPalette.Disabled, QPalette.Shadow, brush8)
        palette14.setBrush(QPalette.Disabled, QPalette.Accent, brush9)
        self.Installed_games_content.setPalette(palette14)
        self.Installed_games_content.setStyleSheet(u"")
        self.Steam_recent_games_7.setWidget(self.Installed_games_content)

        self.verticalLayout_10.addWidget(self.Steam_recent_games_7)


        self.verticalLayout_7.addWidget(self.installed_games_container)

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        self.verticalLayout_6.addWidget(self.scrollArea_2)

        self.tabWidget.addTab(self.Installed_games, "")
        self.Owned_games = QWidget()
        self.Owned_games.setObjectName(u"Owned_games")
        self.verticalLayout_13 = QVBoxLayout(self.Owned_games)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.scrollArea_4 = QScrollArea(self.Owned_games)
        self.scrollArea_4.setObjectName(u"scrollArea_4")
        self.scrollArea_4.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 1198, 560))
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_4.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_4.setSizePolicy(sizePolicy)
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.scrollAreaWidgetContents_4.setPalette(palette15)
        self.verticalLayout_11 = QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 5, 0, 0)
        self.widget_13 = QWidget(self.scrollAreaWidgetContents_4)
        self.widget_13.setObjectName(u"widget_13")
        self.widget_13.setMinimumSize(QSize(0, 350))
        self.widget_13.setMaximumSize(QSize(16777215, 16777215))
        self.widget_13.setBaseSize(QSize(0, 375))
        self.verticalLayout_12 = QVBoxLayout(self.widget_13)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.widget_18 = QWidget(self.widget_13)
        self.widget_18.setObjectName(u"widget_18")
        self.widget_18.setMaximumSize(QSize(16777215, 50))
        self.horizontalLayout_20 = QHBoxLayout(self.widget_18)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName(u"horizontalLayout_20")
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.widget_19 = QWidget(self.widget_18)
        self.widget_19.setObjectName(u"widget_19")
        sizePolicy1.setHeightForWidth(self.widget_19.sizePolicy().hasHeightForWidth())
        self.widget_19.setSizePolicy(sizePolicy1)
        self.horizontalLayout_21 = QHBoxLayout(self.widget_19)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName(u"horizontalLayout_21")
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.owned_games_quantity = QLabel(self.widget_19)
        self.owned_games_quantity.setObjectName(u"owned_games_quantity")
        self.owned_games_quantity.setMaximumSize(QSize(16777215, 16777215))
        self.owned_games_quantity.setFont(font6)
        self.owned_games_quantity.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.owned_games_quantity.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.owned_games_quantity.setMargin(0)
        self.owned_games_quantity.setIndent(15)

        self.horizontalLayout_21.addWidget(self.owned_games_quantity)


        self.horizontalLayout_20.addWidget(self.widget_19)

        self.width_slider_container_2 = QWidget(self.widget_18)
        self.width_slider_container_2.setObjectName(u"width_slider_container_2")
        self.width_slider_container_2.setMaximumSize(QSize(415, 16777215))
        self.horizontalLayout_22 = QHBoxLayout(self.width_slider_container_2)
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName(u"horizontalLayout_22")
        self.horizontalLayout_22.setContentsMargins(9, 4, -1, 0)
        self.horizontalSpacer_9 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_22.addItem(self.horizontalSpacer_9)

        self.set_img_cover_width_owned = QSlider(self.width_slider_container_2)
        self.set_img_cover_width_owned.setObjectName(u"set_img_cover_width_owned")
        sizePolicy5.setHeightForWidth(self.set_img_cover_width_owned.sizePolicy().hasHeightForWidth())
        self.set_img_cover_width_owned.setSizePolicy(sizePolicy5)
        self.set_img_cover_width_owned.setMinimumSize(QSize(0, 0))
        self.set_img_cover_width_owned.setMaximumSize(QSize(16777215, 16777215))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette16.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette16.setBrush(QPalette.Active, QPalette.Shadow, brush12)
        palette16.setBrush(QPalette.Active, QPalette.Link, brush12)
        palette16.setBrush(QPalette.Active, QPalette.Accent, brush12)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette16.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette16.setBrush(QPalette.Inactive, QPalette.Shadow, brush12)
        palette16.setBrush(QPalette.Inactive, QPalette.Link, brush12)
        palette16.setBrush(QPalette.Inactive, QPalette.Accent, brush12)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        palette16.setBrush(QPalette.Disabled, QPalette.Shadow, brush12)
        palette16.setBrush(QPalette.Disabled, QPalette.Link, brush12)
        palette16.setBrush(QPalette.Disabled, QPalette.Accent, brush12)
        self.set_img_cover_width_owned.setPalette(palette16)
        self.set_img_cover_width_owned.setStyleSheet(u"")
        self.set_img_cover_width_owned.setMinimum(94)
        self.set_img_cover_width_owned.setMaximum(1080)
        self.set_img_cover_width_owned.setValue(200)
        self.set_img_cover_width_owned.setOrientation(Qt.Horizontal)

        self.horizontalLayout_22.addWidget(self.set_img_cover_width_owned)

        self.img_cover_width_info_owned = QLabel(self.width_slider_container_2)
        self.img_cover_width_info_owned.setObjectName(u"img_cover_width_info_owned")
        self.img_cover_width_info_owned.setMaximumSize(QSize(16777215, 35))
        self.img_cover_width_info_owned.setBaseSize(QSize(0, 2))
        self.img_cover_width_info_owned.setFont(font1)
        self.img_cover_width_info_owned.setStyleSheet(u"color: rgb(0, 255, 0);\n"
"margin-top: 0.5px;\n"
"")
        self.img_cover_width_info_owned.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.img_cover_width_info_owned.setMargin(0)

        self.horizontalLayout_22.addWidget(self.img_cover_width_info_owned)

        self.horizontalSpacer_10 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_22.addItem(self.horizontalSpacer_10)


        self.horizontalLayout_20.addWidget(self.width_slider_container_2)

        self.search_widget_container_2 = QWidget(self.widget_18)
        self.search_widget_container_2.setObjectName(u"search_widget_container_2")
        sizePolicy1.setHeightForWidth(self.search_widget_container_2.sizePolicy().hasHeightForWidth())
        self.search_widget_container_2.setSizePolicy(sizePolicy1)
        self.search_widget_container_2.setMaximumSize(QSize(415, 16777215))
        self.search_widget_container_2.setLayoutDirection(Qt.LeftToRight)
        self.horizontalLayout_23 = QHBoxLayout(self.search_widget_container_2)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName(u"horizontalLayout_23")
        self.horizontalLayout_23.setContentsMargins(0, 0, 15, 0)
        self.horizontalSpacer_11 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_23.addItem(self.horizontalSpacer_11)

        self.widget_20 = QWidget(self.search_widget_container_2)
        self.widget_20.setObjectName(u"widget_20")
        sizePolicy5.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy5)
        self.widget_20.setStyleSheet(u"border: 2px solid white;;\n"
"border-radius: 15px;\n"
"background-color: rgba(0, 0, 0, 0);")
        self.horizontalLayout_24 = QHBoxLayout(self.widget_20)
        self.horizontalLayout_24.setSpacing(5)
        self.horizontalLayout_24.setObjectName(u"horizontalLayout_24")
        self.horizontalLayout_24.setContentsMargins(10, 2, 10, 2)
        self.label_7 = QLabel(self.widget_20)
        self.label_7.setObjectName(u"label_7")
        sizePolicy1.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy1)
        self.label_7.setMaximumSize(QSize(24, 24))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.Button, brush13)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush13)
        palette17.setBrush(QPalette.Active, QPalette.Window, brush13)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette17.setBrush(QPalette.Inactive, QPalette.Base, brush13)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        palette17.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush13)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush13)
        self.label_7.setPalette(palette17)
        self.label_7.setFont(font7)
        self.label_7.setStyleSheet(u"border: 0;")
        self.label_7.setPixmap(QPixmap(u":/icons/resources/icons/search-white.png"))
        self.label_7.setScaledContents(True)

        self.horizontalLayout_24.addWidget(self.label_7)

        self.search_games_owned = QLineEdit(self.widget_20)
        self.search_games_owned.setObjectName(u"search_games_owned")
        sizePolicy6.setHeightForWidth(self.search_games_owned.sizePolicy().hasHeightForWidth())
        self.search_games_owned.setSizePolicy(sizePolicy6)
        self.search_games_owned.setMaximumSize(QSize(16777215, 16777215))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.Button, brush13)
        palette18.setBrush(QPalette.Active, QPalette.Base, brush13)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush13)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette18.setBrush(QPalette.Inactive, QPalette.Base, brush13)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush13)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush13)
        self.search_games_owned.setPalette(palette18)
        self.search_games_owned.setFont(font8)
        self.search_games_owned.setAcceptDrops(True)
        self.search_games_owned.setLayoutDirection(Qt.LeftToRight)
        self.search_games_owned.setStyleSheet(u"border: 0; margin-bottom: 3px;")
        self.search_games_owned.setFrame(False)
        self.search_games_owned.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.search_games_owned.setDragEnabled(False)

        self.horizontalLayout_24.addWidget(self.search_games_owned)


        self.horizontalLayout_23.addWidget(self.widget_20)


        self.horizontalLayout_20.addWidget(self.search_widget_container_2)


        self.verticalLayout_12.addWidget(self.widget_18)

        self.Steam_recent_games_9 = QScrollArea(self.widget_13)
        self.Steam_recent_games_9.setObjectName(u"Steam_recent_games_9")
        self.Steam_recent_games_9.setEnabled(True)
        self.Steam_recent_games_9.setMinimumSize(QSize(0, 0))
        self.Steam_recent_games_9.setMaximumSize(QSize(16777215, 16777215))
        self.Steam_recent_games_9.setStyleSheet(u"")
        self.Steam_recent_games_9.setFrameShape(QFrame.NoFrame)
        self.Steam_recent_games_9.setFrameShadow(QFrame.Sunken)
        self.Steam_recent_games_9.setLineWidth(2)
        self.Steam_recent_games_9.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Steam_recent_games_9.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Steam_recent_games_9.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.Steam_recent_games_9.setWidgetResizable(True)
        self.Owned_games_content = QWidget()
        self.Owned_games_content.setObjectName(u"Owned_games_content")
        self.Owned_games_content.setEnabled(True)
        self.Owned_games_content.setGeometry(QRect(0, 0, 1198, 509))
        sizePolicy1.setHeightForWidth(self.Owned_games_content.sizePolicy().hasHeightForWidth())
        self.Owned_games_content.setSizePolicy(sizePolicy1)
        self.Owned_games_content.setMinimumSize(QSize(0, 0))
        self.Owned_games_content.setMaximumSize(QSize(16777215, 16777215))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.Base, brush7)
        palette19.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette19.setBrush(QPalette.Active, QPalette.Shadow, brush8)
        palette19.setBrush(QPalette.Active, QPalette.Accent, brush9)
        palette19.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette19.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette19.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        palette19.setBrush(QPalette.Disabled, QPalette.Shadow, brush8)
        palette19.setBrush(QPalette.Disabled, QPalette.Accent, brush9)
        self.Owned_games_content.setPalette(palette19)
        self.Owned_games_content.setStyleSheet(u"")
        self.Steam_recent_games_9.setWidget(self.Owned_games_content)

        self.verticalLayout_12.addWidget(self.Steam_recent_games_9)


        self.verticalLayout_11.addWidget(self.widget_13)

        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)

        self.verticalLayout_13.addWidget(self.scrollArea_4)

        self.tabWidget.addTab(self.Owned_games, "")
        self.Options = QWidget()
        self.Options.setObjectName(u"Options")
        self.verticalLayout_16 = QVBoxLayout(self.Options)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.scrollArea_5 = QScrollArea(self.Options)
        self.scrollArea_5.setObjectName(u"scrollArea_5")
        self.scrollArea_5.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollAreaWidgetContents_5 = QWidget()
        self.scrollAreaWidgetContents_5.setObjectName(u"scrollAreaWidgetContents_5")
        self.scrollAreaWidgetContents_5.setGeometry(QRect(0, 0, 1180, 542))
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_5.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_5.setSizePolicy(sizePolicy)
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette20.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette20.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette20.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.scrollAreaWidgetContents_5.setPalette(palette20)
        self.verticalLayout_14 = QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.verticalLayout_14.setContentsMargins(0, 5, 0, 0)
        self.widget_16 = QWidget(self.scrollAreaWidgetContents_5)
        self.widget_16.setObjectName(u"widget_16")
        sizePolicy1.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy1)
        self.widget_16.setMinimumSize(QSize(0, 350))
        self.widget_16.setMaximumSize(QSize(16777215, 16777215))
        self.widget_16.setBaseSize(QSize(0, 375))
        self.horizontalLayout_14 = QHBoxLayout(self.widget_16)
        self.horizontalLayout_14.setSpacing(10)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.widget_14 = QWidget(self.widget_16)
        self.widget_14.setObjectName(u"widget_14")
        sizePolicy2.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy2)
        self.horizontalLayout_15 = QHBoxLayout(self.widget_14)
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.label_6 = QLabel(self.widget_14)
        self.label_6.setObjectName(u"label_6")
        sizePolicy2.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy2)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.label_6.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_15.addWidget(self.label_6)

        self.launch_widget_on_start = QPushButton(self.widget_14)
        self.launch_widget_on_start.setObjectName(u"launch_widget_on_start")
        sizePolicy2.setHeightForWidth(self.launch_widget_on_start.sizePolicy().hasHeightForWidth())
        self.launch_widget_on_start.setSizePolicy(sizePolicy2)
        self.launch_widget_on_start.setMinimumSize(QSize(0, 0))
        self.launch_widget_on_start.setMaximumSize(QSize(16777215, 16777215))
        self.launch_widget_on_start.setFont(font7)
        self.launch_widget_on_start.setCursor(QCursor(Qt.PointingHandCursor))
        self.launch_widget_on_start.setStyleSheet(u"color: rgb(255, 0, 0);")

        self.horizontalLayout_15.addWidget(self.launch_widget_on_start)


        self.horizontalLayout_14.addWidget(self.widget_14)


        self.verticalLayout_14.addWidget(self.widget_16)

        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)

        self.verticalLayout_16.addWidget(self.scrollArea_5)

        self.tabWidget.addTab(self.Options, "")

        self.horizontalLayout_7.addWidget(self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Games Vault", None))
        self.user_avatar.setText("")
        self.user_display_name.setText(QCoreApplication.translate("MainWindow", u"Guest", None))
        self.user_total_playtime.setText(QCoreApplication.translate("MainWindow", u"Total playtime: 0", None))
        self.recent_games_refresh_info.setText(QCoreApplication.translate("MainWindow", u"Refresh in: 0", None))
        self.label_2.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Steam", None))
        self.steam_dir_info.setText(QCoreApplication.translate("MainWindow", u"\u2718 Directory not selected", None))
        self.label_3.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Epic Games", None))
        self.epic_dir_info.setText(QCoreApplication.translate("MainWindow", u"\u2718 Directory not selected", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Last_played), QCoreApplication.translate("MainWindow", u"Last Played", None))
        self.installed_games_quantity.setText(QCoreApplication.translate("MainWindow", u"0 Games", None))
        self.open_widget.setText(QCoreApplication.translate("MainWindow", u"Widget \u29c9", None))
        self.img_cover_width_info.setText(QCoreApplication.translate("MainWindow", u"140px", None))
        self.label_5.setText("")
        self.search_games.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Installed_games), QCoreApplication.translate("MainWindow", u"Installed", None))
        self.owned_games_quantity.setText(QCoreApplication.translate("MainWindow", u"0 Games", None))
        self.img_cover_width_info_owned.setText(QCoreApplication.translate("MainWindow", u"200px", None))
        self.label_7.setText("")
        self.search_games_owned.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Owned_games), QCoreApplication.translate("MainWindow", u"Owned", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Launch widget on start", None))
        self.launch_widget_on_start.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Options), QCoreApplication.translate("MainWindow", u"\u26ed Options", None))
    # retranslateUi

